<?xml version="1.0" encoding="utf-8"?><Database Name="QL_MyPham" Class="DbQLMPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-VJ74VHTT;Initial Catalog=QL_MyPham;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_MyPhamConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs">
    <Type Name="CHITIETPHIEUNHAP">
      <Column Name="MAPN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="PHIEUNHAP_CHITIETPHIEUNHAP" Member="PHIEUNHAP" ThisKey="MAPN" OtherKey="MAPN" Type="PHIEUNHAP" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETPHIEUNHAP" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUCSP" Member="DANHMUCSPs">
    <Type Name="DANHMUCSP">
      <Column Name="MADM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DANHMUCSP_SANPHAM" Member="SANPHAMs" ThisKey="MADM" OtherKey="MADM" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.GIAMGIA" Member="GIAMGIAs">
    <Type Name="GIAMGIA">
      <Column Name="MAGG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENGG" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PHANTRAMGG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYBD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NGAYKT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="GIAMGIA_HOADON" Member="HOADONs" ThisKey="MAGG" OtherKey="MAGG" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENHD" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NGUOILAP" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MAGG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADON" />
      <Association Name="GIAMGIA_HOADON" Member="GIAMGIA" ThisKey="MAGG" OtherKey="MAGG" Type="GIAMGIA" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_HOADON" Member="NGUOIDUNG" ThisKey="MAND" OtherKey="MAND" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="MAND" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TAIKHOAN" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="THOIGIANTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NGUOIDUNG_HOADON" Member="HOADONs" ThisKey="MAND" OtherKey="MAND" Type="HOADON" />
      <Association Name="NGUOIDUNG_QUYENND" Member="QUYENNDs" ThisKey="MAND" OtherKey="MAND" Type="QUYENND" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MANCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="NGUOILIENHE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MANCC" OtherKey="MANCC" Type="PHIEUNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="MAPN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MANCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PHIEUNHAP_CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs" ThisKey="MAPN" OtherKey="MAPN" Type="CHITIETPHIEUNHAP" />
      <Association Name="NHACUNGCAP_PHIEUNHAP" Member="NHACUNGCAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUYEN" Member="QUYENs">
    <Type Name="QUYEN">
      <Column Name="MAQUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENQUYEN" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="QUYEN_QUYENND" Member="QUYENNDs" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="QUYENND" />
    </Type>
  </Table>
  <Table Name="dbo.QUYENND" Member="QUYENNDs">
    <Type Name="QUYENND">
      <Column Name="MAND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAQUYEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NGUOIDUNG_QUYENND" Member="NGUOIDUNG" ThisKey="MAND" OtherKey="MAND" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="QUYEN_QUYENND" Member="QUYEN" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="QUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MADM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="XUATXU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="THUONGHIEU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HSD" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="HINH" Type="System.String" DbType="Char(150) NOT NULL" CanBeNull="false" />
      <Association Name="SANPHAM_CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETPHIEUNHAP" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETHOADON" />
      <Association Name="DANHMUCSP_SANPHAM" Member="DANHMUCSP" ThisKey="MADM" OtherKey="MADM" Type="DANHMUCSP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>